:schedule:
  invoice_generation:
    cron: '10 23 28 * *' # all 28th we'll trigger the invoicing process
    class: InvocingService
    description: 'This job generates invocing for all customers for a given period'
